
services:
  # Next.js Frontend Container
  nextjs:
    container_name: ecs-performance-nextjs
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - REVALIDATE_SECRET=dev-secret-key-12345
    volumes:
      - ../../apps/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - ecs-performance-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Hono Backend Container
  backend:
    container_name: ecs-performance-backend
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/appdb
      - NEXTJS_URL=http://nextjs:3000
      - REVALIDATE_SECRET=dev-secret-key-12345
    volumes:
      - ../../apps/backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecs-performance-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Container
  postgres:
    container_name: ecs-performance-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecs-performance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ecs-performance-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local